name: custom_video_player
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: 0.10.8+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter